name: PHP Composer

on:
  push:
    branches: [ master ]
 
jobs:
  make-lint:
    name: Make lint
    defaults:
      run:
        shell: bash
    runs-on: macos-latest
    steps:
      - name: run make lint
        run: make make lint




    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
